CREATE TABLE IF NOT EXISTS past_meet_ups (
    id UUID PRIMARY KEY NOT NULL,
    paper_id UUID REFERENCES papers(id),
    date DATE NOT NULL,
    link TEXT NOT NULL,
    location TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS past_meet_ups_date_index ON past_meet_ups (date);
